### ISSUE TITLE
Modül hatası

### ISSUE THREAD

**Issue by aligundogdu** [miratcan/FriendFeed-Tools#2]
Merhaba,

python migrate.py komutunu verdiğimde karşılaştığım hata şu şekilde 

Traceback (most recent call last):
  File "migrate.py", line 1, in <module>
    from migraters import FriendFeedHtmlMigration
ImportError: No module named migraters

teşekkürler.

**Comment by miratcan** [comment]
OS nedir? Windows?

**Comment by miratcan** [comment]
migraters dosyasını eklememişim, şimdi git pull yapıp alabilirsin :)

**Comment by aligundogdu** [comment]
Teşekkürler.
